// generated by Fast Light User Interface Designer (fluid) version 1.0301

#include <FL/Fl_Group.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl.H>


int main(int argc, char **argv) {
  Fl_Double_Window win( 100, 100, 800, 800, "Multi Document Application" );
  
  win.end();
  
  win.show(argc, argv);
  return Fl::run();
}
